from enum import Enum


class HouseholdType(Enum):
    TWO_ADULTS_YOUNGER_THAN_65 = 6
    TWO_ADULTS_ONE_AT_LEAST_65 = 7
    THREE_OR_MORE_ADULTS = 8
    SINGLE_PARENT_WITH_CHILDREN = 9
    TWO_ADULTS_WITH_ONE_CHILD = 10
    TWO_ADULTS_WITH_TWO_CHILDREN = 11
    TWO_ADULTS_WITH_AT_LEAST_THREE_CHILDREN = 12
    THREE_OR_MORE_ADULTS_WITH_CHILDREN = 13
    ONE_ADULT_YOUNGER_THAN_64 = 51
    ONE_ADULT_OLDER_THAN_65 = 52
