name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - docs
      - main

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.x'

      - name: Install h5py dependencies
        run: |
          sudo apt-get install libhdf5-dev    
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-jupyter==0.25.1 mistune==3.0.2 nbconvert==7.14.0 mike
          pip install .
          pip install -r docs/requirements.txt
          echo "Installed package versions:"
          pip freeze | grep -E "mistune|nbconvert|mkdocs-jupyter|mike"
          
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Build and deploy docs with mike
        run: 
          mike deploy --push latest