name: Deploy docs to Google Storage

on:
  push:
    branches:
      - gh-pages
      - docs
      - main

  workflow_dispatch:

env:
  GCS_BUCKET: macromodel-docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Auth GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Upload to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: .
          destination: ${{ env.GCS_BUCKET }}
          parent: false
          rsync_args: --exclude=.git
