# Makes sure that the code is properly formatted with black and isort.

name: Style Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install h5py dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libhdf5-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    - name: Check code formatting with black
      run: |
        black --check --config="pyproject.toml" .
    - name: Check code formatting with isort
      run: |
        isort . --check-only --settings-path pyproject.toml